### ISSUE TITLE
bump version

### ISSUE THREAD

**Issue by 1N50MN14** [nathanboktae/robust-websocket#3]
Hey @nathanboktae thanks for the well thought of module, specially in regards to navigator online/offline.

Mind bumping version and publishing on npm (url as a function is something that I rely on)? 

Many thanks

**Comment by nathanboktae** [comment]
Thanks for the nudge. I also decided to bump it up to `1.0.0` since this package is stable - but no breaking changes, the one you mentioned. Thanks!

**Comment by 1N50MN14** [comment]
Awesome thank you!
